language: node_js
node_js:
  - 'stable'

script:
  - echo VUE_APP_GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID > .env.production.local
  - npm run build
  - npm run lint

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_1e5f78a5e17c_key -iv $encrypted_1e5f78a5e17c_iv -in deploy_key.enc -out /home/travis/.ssh/id_ed25519 -d;
      chmod 600 ~/.ssh/id_ed25519;
      echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config;
      git config --global user.email "48376527+knctprolab-bot@users.noreply.github.com";
      git config --global user.name "knctprolab-bot";
      git clone git@github.com:ProgrammingLab/kurume-nct.com.git;
      cd kurume-nct.com;
      rm -rf ./js/ ./css/ ./img/;
      cp -aR ../dist/* .;
      git add --all;
      git commit -m "built by Travis CI JOB #$TRAVIS_JOB_NUMBER";
      git push origin master;
    fi

notifications:
  email:
    on_success: never
    on_failure: always
